server:
  port: 8080

spring:
  application:
    name: edumonitor-api-service

  datasource:
    url: jdbc:postgresql://localhost:5555/edumonitor
    username: edumonitor
    password: edumonitor
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_BEFORE_PRODUCTION_1234567890"
  expiration-ms: 86400000

logging:
  level:
    com.sdlms: DEBUG
    org.springframework.security: INFO
